bonsai-rx/bonsai

Bonsai.Editor/EditorForm.cs, Bonsai.Editor/ExportHelper.cs, Bonsai.Editor/GraphView/GraphViewControl.cs, Bonsai.Editor/WorkflowExporter.cs, Bonsai/Launcher.cs, Bonsai/Program.cs
This PR refactors the SVG and image export functions in preparation for resolving #929. We decided to postpone the full functionality to the next release cycle, but it would be useful to start preparing the code base.
This PR also standardizes export sizes to avoid DPI-dependent vector exports.
Fixes #939
=> Refactor and standardize SVG export functions

Bonsai.Vision/CropCenter.cs, Bonsai.Vision/IplImageHelper.cs, Bonsai.Vision/ResizeCanvas.cs
This PR aims to provide functionality to make it easier to crop fixed-size rectangular regions around specified image points for further processing.
Fixes #980
=> Allow cropping fixed-size rectangular regions around specified image points

Bonsai.Configuration/ConfigurationHelper.cs, Bonsai.Configuration/ScriptExtensions.cs, Bonsai.Editor/Bonsai.Editor.csproj, Bonsai.Editor/DocumentationHelper.cs, Bonsai.Editor/EditorDialog.cs, Bonsai.Editor/EditorForm.Designer.cs, Bonsai.Editor/EditorForm.cs, Bonsai.Editor/GraphView/WorkflowGraphView.Designer.cs, Bonsai.Editor/GraphView/WorkflowGraphView.cs, Bonsai.Editor/GraphView/WorkflowGraphView.resx, Bonsai.Editor/IDocumentationProvider.cs, Bonsai/DependencyInspector.cs, Bonsai/DocumentationProvider.cs, Bonsai/Launcher.cs, Bonsai/ScriptExtensionsEnvironment.cs
This PR adds built-in editor integration for searching the reference documentation website. Following the DocFX standard, it looks for the `xrefmap.yml` file in the project website of the package containing the module. If the index exists, it then looks up the UID of the target operator to retrieve the corresponding documentation page.
Fixes #936
=> Add built-in integration for community documentation

Bonsai.Editor/GraphView/WorkflowEditorControl.cs
This PR allows closing the editor tab with a middle mouse click on the tab. Existing keyboard shortcuts for closing the tab are preserved.
Fixes #963
=> Allow closing editor tab with middle mouse click

Bonsai.Configuration/ConfigurationHelper.cs, Bonsai/Program.cs
This PR introduces a runtime assembly resolution path without locking the assembly file on disk by leveraging `File.ReadAllBytes` to load the assembly into memory without a file reference. This allows the package manager UI to use installed local dependencies while still allowing those same dependencies to be updated.
**Caveat:** _code used specifically by the package manager UI can never depend on `Assembly.Location` or similar properties in the `Assembly` class that depend on loading the assembly from a file path._
Fixes #1048
=> Load package manager dependencies without assembly lock

Bonsai.Core/Bonsai.Core.csproj, Bonsai.Core/WorkflowBuilder.cs
This PR introduces .NET standard support for `Bonsai.Core`. A conditional multi-targeting package dependency strategy was used to allow both backwards compatibility for .NET framework projects and evolution of `System.Reactive` for any new cross-platform dependents.
Fixes #1050
=> Add netstandard build target for core assembly

Bonsai.Editor/Layout/LayoutHelper.cs
This PR ensures propagation of nested mashup source mapping settings to the top-level layout file. On deserialization, any nested settings are paired up with specified visualizer mappings as needed.
Fixes #1060
=> Ensure nested mashup sources are always serialized

Bonsai.Core/Reactive/Slice.cs
This PR reimplements the `Slice` operator to follow the behavior of `Take` and terminate the sequence as early as possible after the `Stop` condition is reached. Parameter ranges are also validated.
Fixes #930
=> Align semantics of Slice operator with Take

Bonsai.Editor/EditorForm.Designer.cs, Bonsai.Editor/EditorForm.cs, Bonsai.Editor/EditorForm.resx, Bonsai.Editor/GraphModel/WorkflowBuilderExtensions.cs, Bonsai.Editor/GraphModel/WorkflowQuery.cs
This PR adds basic support for finding toolbox elements in the workflow. The current implementation works much like the "Find Next" and "Find Previous" logic common to text editors, where the workflow view will highlight the subsequent match in topological order. Search is initiated from the toolbox with support for three different toolbox element types:
* Subject: If a subject node is selected, all references (subscribe or multicast) matching the selected name will be found.
* Workflow: If a workflow node is selected, all `IncludeWorkflow` operators matching the selected workflow name will be found.
* Other: If any other node is selected, all workflow operators matching the type of the selected toolbox node will be found.
The selected shortcut key is F3 for "Find Next" and Shift+F3 for …
=> Add support for finding toolbox elements

Bonsai.Core/Expressions/CombinatorBuilder.cs, Bonsai.Core/ResetCombinatorAttribute.cs, Bonsai.Vision/Drawing/AddImage.cs, Bonsai.Vision/Drawing/DrawContours.cs, Bonsai.Vision/Drawing/FillPolygon.cs, Bonsai.Vision/Drawing/LineChart.cs, Bonsai.Vision/Drawing/Path.cs, Bonsai.Vision/Drawing/PolyLine.cs
This PR introduces the `ResetCombinatorAttribute` as an explicit opt-in requirement for resetting non-serializable combinator properties. This allows classes to request a reset of their volatile runtime state at workflow build time without compromising performance or introducing unexpected behavior for all other regular combinators.
Fixes #659
=> Require opt-in attribute to reset combinator

Bonsai.Core/Bonsai.Core.csproj, Bonsai.Core/Reactive/Concurrency/CurrentThreadScheduler.cs, Bonsai.Core/Reactive/Concurrency/DefaultScheduler.cs, Bonsai.Core/Reactive/Concurrency/EventLoopScheduler.cs, Bonsai.Core/Reactive/Concurrency/ImmediateScheduler.cs, Bonsai.Core/Reactive/Concurrency/NewThreadScheduler.cs, Bonsai.Core/Reactive/Concurrency/SchedulerMapping.cs, Bonsai.Core/Reactive/Concurrency/SchedulerMappingConverter.cs, Bonsai.Core/Reactive/Concurrency/TaskPoolScheduler.cs, Bonsai.Core/Reactive/Concurrency/ThreadPoolScheduler.cs, Bonsai.Core/Reactive/ObserveOn.cs, Bonsai.Core/Reactive/SubscribeOn.cs, Bonsai.Editor/Bonsai.Editor.csproj, Bonsai.System/Bonsai.System.csproj
This PR adds operators for creating objects that schedule units of work in various concurrency platforms. It also adds support to control concurrency for operator notifications and subscription logic using the `ObserveOn` and `SubscribeOn` operators.
Schedulers are specified as properties in each of the operators which can either be externalized and assigned dynamically from user-specified sequences, or from a drop-down list of well-known default scheduler types.
Fixes #1081
=> Add scheduler and concurrency control operators

Bonsai.NuGet.Design/Bonsai.NuGet.Design.csproj, Bonsai.NuGet.Design/GalleryDialog.Designer.cs, Bonsai.NuGet.Design/PackageBuilderDialog.cs, Bonsai/Bonsai.csproj
This PR fixes a small number of layout issues with the gallery and package export dialogs, ensuring uniformity with other package manager dialogs.
Fixes #1096
=> Fix layout for gallery and package export dialogs

Bonsai.Shaders.Rendering/Bonsai.Shaders.Rendering.csproj, Bonsai.Shaders.Rendering/SceneConfiguration.cs
This PR adds drag and drop support for more formats compatible with the Open Asset Import Library, to make it easier to import multiple files.
Fixes #1124
=> Add support for COLLADA, FBX and STL formats

Bonsai.Scripting.IronPython.Design/Bonsai.Scripting.IronPython.Design.csproj, Bonsai.Scripting.IronPython/Bonsai.Scripting.IronPython.csproj, Bonsai.Scripting.IronPython/PythonEngine.cs
This PR adds support for Python scripts to be included in the standard scripting extension folders used by the editor for both C# and workflow extensions.
Fixes #1143
=> Add extension folders to IronPython search path

Bonsai.Editor/EditorForm.cs, Bonsai.Editor/GraphView/WorkflowGraphView.cs
This PR fixes pending issues when drag and dropping workflow files into the graph view, which were causing crashes and unexpected loss of information.
Fixes #1104 
Fixes #1105
=> Fix drag and dropping of workflow files into the graph view

Bonsai.Editor/GraphModel/UpgradeHelper.cs
This PR extends the functionality of upgrading included workflows on ungrouping also to embedded workflows.
There is some redundancy on code used for accessing the embedded resource stream that should probably be refactored into the core API. However, the code is not too complex and this is a critical bit of functionality for package maintainers, so the decision was made to port a simplified version from `IncludeWorkflowBuilder`.
Fixes #1126
=> Ensure embedded workflows also upgrade on ungroup

Bonsai.Editor/GraphModel/UpgradeHelper.cs
This PR ensures that upgrading disabled nodes does not cause the node to be re-enabled.
The fix is actually more involved than expected since there is currently no good way to convert / replace individual builder nodes in a way that keeps their sort order. As a temporary workaround we are running a local convert routine just for the individual upgraded node, but this would greatly benefit from refactoring the core API in the future to more easily support such conversion operations, especially if growing decorator support is anticipated.
Fixes #1097
=> Ensure upgrading does not re-enable disabled nodes

Bonsai/WorkflowElementLoader.cs
This PR takes the first step in associating metadata information with workflows embedded in assembly resources. The idea is to use a metadata type with the same fully qualified name as the workflow embedded resource and decorate this type with attributes.
In this first application we allow for reading the `ObsoleteAttribute` in the metadata type to allow hiding deprecated workflows from the toolbox.
Fixes #1109
=> Allow deprecation of embedded workflows using assembly metadata type

Bonsai.Editor/Bonsai.Editor.csproj, Bonsai.Editor/GraphModel/WorkflowEditor.cs
This PR ensures the upgrade routine works correctly when ungrouping included workflows by reverting the upgraded workflow to its non-inspectable form.
Fixes #1148
=> Ensure correct upgrade of inspectable workflows

Bonsai.Editor/GraphModel/UpgradeHelper.cs, Bonsai/WorkflowElementLoader.cs
When ungrouping an include workflow, the file may be quickly checked for whether an upgrade is required. This PR ensures that this check does not keep the file locked when re-saving the workflow. Apparently `XmlReader` does not close source streams by default, unless specific reader settings are activated.
Fixes #1163
=> Avoid locked file access when upgrading and re-saving extensions

Bonsai.Editor/EditorForm.cs
This PR ensures that the initial directory for the open and save dialogs on the main editor is consistent with the current working directory set on initialization. This aims to prevent saving workflows by mistake across different environments.
Fixes #1135
=> Ensure initial and current directories are equal

Bonsai.Editor/EditorForm.cs
This PR further restricts the editing of design-only properties to non-include workflows. Design-only properties are concerned with controlling structural changes to the expression tree itself. For example, the `Path` property in an included workflow node is itself a design-only property and changing it causes significant restructuring to the workflow expression tree.
It is expected that such structural changes are not allowed inside included workflows, since they are meant to be read-only immutable specifications.
Fixes #899
=> Disable editing of design-only properties inside included workflows

Bonsai.Templates/Bonsai.EnvironmentTemplate/.template.config/template.json, Bonsai.Templates/Bonsai.EnvironmentTemplate/Setup.cmd, Bonsai.Templates/Bonsai.EnvironmentTemplate/Setup.ps1, Bonsai.Templates/Bonsai.PackageTemplate/.template.config/template.json, Bonsai.Templates/Bonsai.Templates.csproj
This PR adds support for bootstrapping a new self-contained Bonsai environment using the `dotnet` templating system, PowerShell, and GitHub releases.
To install:
```
dotnet new -i Bonsai.Templates
```
Create a new environment folder:
```
dotnet new bonsaienv -o bonsai
```
If there is an existing `Bonsai.config` and/or `NuGet.config` in the folder, these will be used as part of the environment reconstruction process. In this case, it is enough to navigate to the folder where `Bonsai.config` is and simply run:
```
dotnet new bonsaienv
```
=> Add dotnet template for creating a new bonsai environment

Bonsai.System/Bonsai.System.csproj, Bonsai.System/IO/CsvWriter.cs
This PR overrides the default maximum number of significant digits when formatting floating-point values to ensure they can round-trip successfully using `CsvReader` or other applications.
The formatting defaults of the [General format specifier](https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings?redirectedfrom=MSDN#GFormatString) use G7 and G15 respectively as max precision defaults on .NET framework.
In the guidelines for using the [Round-trip format specifier](https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings?redirectedfrom=MSDN#RFormatString) the recommendation is to use G9 and G17 respectively for maximum fidelity.
The defaults have been fixed in .NET Core 3.0 onwards, but we need the override until …
=> Increase default max number of significant digits for floating-point values in CsvWriter

Bonsai.Core.Tests/Constants.cs, Bonsai.Core.Tests/TypeMappingTests.cs, Bonsai.Core.Tests/WorkflowBuilderTests.cs, Bonsai.Core/Bonsai.Core.csproj, Bonsai.Core/WorkflowBuilder.cs
`WorkflowBuilder` serialization procedure has been modified to walk up the inheritance tree of each extension type to search for any base types with explicit `XmlTypeAttribute` declarations. If any exist, they are explicitly added to the set of serializable extension types.
This prevents overly verbose inline XML namespace declarations for properties provided by base types which are not directly used elsewhere in the workflow.
Fixes #1056
=> Reuse top-level prefix for all extension base types with explicit XML type declarations

Bonsai.Core.Tests/WorkflowBuilderTests.cs, Bonsai.Core/WorkflowBuilder.cs
This PR allows generic type resolution of `TypeMapping` properties in operators outside the core namespace. This is to support automatic code generation frameworks (e.g. for the Harp protocol) where types can benefit from being co-opted for operations which do not require an instance, but just a mapping on the type.
All other uses of `TypeMapping` remain reserved, and libraries should not rely on any internal features of the type.
Fixes #1277
=> Allow generic type resolution of TypeMapping values outside the core namespace

Bonsai.Design/Bonsai.Design.csproj, Bonsai.Design/TypeMappingEditor.cs
This PR adds support for type mapping overload inference for polymorphic combinators. This allows `InputMapping` operators to select target overloads when the downstream operator is a polymorphic combinator builder. In this case, `InputMapping` will find overloads in the selected concrete type.
This will allow libraries relying on auto-generated polymorphic types to expose use of those types as if they were first-class operators in the language.
=> Allow overload inference for polymorphic operators

Bonsai.Core.Tests/WorkflowBuilderTests.cs, Bonsai.Core/WorkflowBuilder.cs
This PR ensures that clashing XML namespace prefix declarations are always resolved within a single workflow file by adding a counter suffix. XML namespace prefixes are just shorthand for the full XML qualified namespace, so there is no need to prevent workflows from serializing correctly just because of package clashes on preferred prefix.
Fixes #1287
=> Ensure unique XML namespace prefix declarations

Bonsai.Core.Tests/SubjectTests.cs, Bonsai.Core/Reactive/Subjects/ResourceSubject.cs
This PR adds a guard on `ResourceSubject` dispose to avoid throwing if the source sequence terminated exceptionally. In this situation, the exception will be propagated to the downstream observer regardless, and calling `Dispose` is simply a cleanup side-effect.
Fixes #1256
=> Avoid throwing on ResourceSubject dispose if source sequence terminated exceptionally

Bonsai.Core/Bonsai.Core.csproj, Bonsai.Core/Expressions/ExpressionBuilder.cs
This PR ensures that non-polymorphic properties of the base type get search priority over properties of the polymorphic operator. This allows exposing externalizable properties of both the base type and polymorphic operator type.
The proposed implementation uses a simple reflection search for public properties to disambiguate whether it is worth performing polymorphic property search. A caveat of this implementation is that in cases where the polymorphic operator exposes a property with the same name of a non-polymorphic property in the base type, the non-polymorphic property will be preferred.
Fixes #1305
=> Ensure priority of base non-polymorphic properties

Bonsai.Configuration/ScriptExtensions.cs
This PR adds support for the dynamic keyword and dynamic object runtime binding for interfacing with external scripting packages such as Python.NET. A reference to the `netstandard` assembly was also added to ensure general package compatibility.
Fixes #1238
=> Add support for dynamic keyword and dynamic object binding in C# scripts

Bonsai.Core/ObservableCombinators.cs
This PR fixes the behavior of the `Gate` operator to be consistent with common language patterns re. subscription. The `Gate` operator in Rx can be called either with a factory overload, where a new subscription is created for each gate trigger, or with a single subscription to an event sequence, where each notification triggers the gate.
The latter overload is more consistent with the rules of similar operators such as `WindowTrigger`. In general one can use the `Defer` operator if the former behavior is required. Alternatively, a new variant of the `Gate` operator can be exposed in the future which surfaces the factory overload through a nested operator.
Fixes #1206
=> Ensure single subscription to Gate opening events

Bonsai.Editor/EditorForm.cs, Bonsai.Editor/EditorSettings.cs, Bonsai.Editor/GraphModel/ElementHelper.cs, Bonsai.Editor/GraphView/WorkflowEditorControl.Designer.cs, Bonsai.Editor/GraphView/WorkflowEditorControl.cs, Bonsai.Editor/GraphView/WorkflowGraphView.cs, Bonsai.Editor/Properties/Resources.Designer.cs, Bonsai.Editor/Properties/Resources.resx, Bonsai.Editor/RecentlyUsedFile.cs
This PR extends the WebView panel functionality used to render annotations to support in-editor browsing of operator documentation. This allows for convenient access to technical references and tutorial examples rendered inline with the workflow.
Support for setting a preferred browser color theme is provided, although it is up to the docs website to support theming. Access to browsing the docs outside of the editor is still supported by using the `Ctrl` modifier, e.g. `Ctrl+F1` will open the docs for the relevant operator in a new external browser tab.
Fixes #1208
=> Add support for in-editor docs browser

.editorconfig, Bonsai.Core/Expressions/AnnotationBuilder.cs, Bonsai.Design/AnnotationBuilderEditorDialog.Designer.cs, Bonsai.Design/AnnotationTextEditor.cs, Bonsai.Editor/Bonsai.Editor.csproj, Bonsai.Editor/GraphView/MarkdownConvert.cs, Bonsai.Editor/GraphView/WorkflowEditorControl.cs, Bonsai.Editor/GraphView/WorkflowGraphView.cs, Bonsai.Editor/Resources/WebView/base.css, Bonsai.Editor/Resources/WebView/dark-theme.css, Bonsai.Editor/Resources/WebView/light-theme.css
This PR improves the experience of editing annotations:
- The markdown editor now starts selected on launch, to allow immediate typing.
- If an annotation is currently rendered it will also be refreshed after editing.
- The converter now avoids overriding the default line height.
- UI type editor is added to the `Text` property.
- Add basic support for dark theme.
Fixes #1360
=> Improved support for editing annotations

Bonsai.Core/Expressions/HasFlagBuilder.cs
This PR introduces a new binary operator `HasFlag` which can be used to test whether specified bit fields are set on all elements of an observable sequence. The implementation has also been extended to allow testing the provided flag values directly against raw primitive types (e.g. numeric types), but the "flag" operand (the property value) must always be an enum.
=> Add support for the HasFlag operator

Bonsai.Editor/EditorForm.cs
This PR extends documentation search to polymorphic operators. The goal is to provide documentation directly for the currently selected function. This makes it easier to understand and explore reference documentation for existing workflows which make heavy use of the polymorphic operator pattern.
Fixes #1313
=> Add support for polymorphic operator docs

Bonsai.Editor.Tests/EditorHelper.cs, Bonsai.Editor.Tests/WorkflowEditorTests.cs, Bonsai.Editor/GraphModel/WorkflowEditor.cs
This PR fixes a subtle issue where replaced nodes would be assigned a different index in the order. The issue was caused by assigning an index to the delete operation, but not to the creation operation. Nodes might therefore be inserted at the end of the workflow and cause an index mismatch in the corresponding delete operation.
=> Ensure replaced nodes keep the same index

Bonsai.Configuration/ScriptExtensions.cs
This PR adds [`System.Numerics`](https://learn.microsoft.com/en-us/dotnet/api/system.numerics) to the set of default assembly references included when building local scripts. This allows access to this small yet powerful SIMD-accelerated library for vector and matrix computations.
=> Add support for using System.Numerics namespace in local scripts

Bonsai.Editor/GraphView/WorkflowGraphView.cs
This PR restricts the group context menu to display only core nested operators. There is currently no easy way to visually scale the context menu to an arbitrary number of items, and as the number of nested operators is expected to increase there is now a concrete possibility for this menu to become cluttered.
As we explore different ways to assist discovery of nested operators defined in external packages, we are for the moment restricting their display in the group context menu. Any nested operator can still be placed directly from the toolbox, simply by searching the operator name, as with any other operator, and then either right-clicking and selecting the group option, or using `Ctrl+Enter`.
Fixes #1347
=> Limit group context menu to core nested operators

Bonsai.System/Bonsai.System.csproj, Bonsai.System/IO/FileSink.cs, Bonsai.System/IO/StreamSink.cs
This PR introduces a new protected overload for both `StreamSink` and `FileSink` operators allowing derived classes to specify a custom base path for created files. This will enable custom writers to demultiplex reactive sequences into multiple files based on dynamically specified names, e.g. using the keys of an `IGroupedObservable`.
Fixes #1309
=> Allow derived IO writer classes to specify base path

Bonsai.Core.Tests/TopologicalSortTests.cs, Bonsai.Core/Dag/TopologicalSort.cs, Bonsai.Editor.Tests/WorkflowEditorTests.cs, Bonsai.Editor/GraphModel/WorkflowEditor.cs
This PR adds regression tests for edge cases involving topological sorting and specific editor actions such as ungrouping passthrough nested nodes. Fixes are also pushed for each case.
=> Regression testing for sorting and editor changes

Bonsai.Configuration/CommandLineParser.cs, Bonsai.Editor/TypeDefinitionProvider.cs, Bonsai.Editor/TypeVisualizerDescriptor.cs, Bonsai/AppResult.cs, Bonsai/Bonsai.csproj, Bonsai/DependencyInspector.cs, Bonsai/Launcher.cs, Bonsai/LoaderResource.cs, Bonsai/PackageAssemblyResolver.cs, Bonsai/Program.cs, Bonsai/Properties/launchSettings.json, Bonsai/ReflectionHelper.cs, Bonsai/TypeVisualizerLoader.cs, Bonsai/WorkflowElementCategoryConverter.cs, Bonsai/WorkflowElementLoader.cs, README.md
This PR rewrites several aspects of the bootstrapper executable to avoid depending on `AppDomain`. Instead, assembly metadata is inspected using [MetadataLoadContext](https://learn.microsoft.com/en-us/dotnet/standard/assembly/inspect-contents-using-metadataloadcontext) and isolated editor sessions are implemented using child processes spawned from the top-level executable.
This is expected to improve both the cross-platform experience of the current editor, and facilitate the transition to .NET 6 where support for multiple `AppDomain` instances has been removed entirely. Other benefits include proper cleanup of loaded native dependencies (process tear-down will unload both native and managed dependencies) and also resolution of specific issues with drivers crashing when spawned from child …
=> Rewrite bootstrapper logic to avoid relying on AppDomain

Bonsai.Editor/WorkflowRunner.cs, Bonsai.Player/Program.cs
This PR redirects the stack traces for all unhandled exceptions in headless runners (e.g. player or --no-editor flag) to stderr. This allows for an easier separation of outputs for CLI applications. For example, from powershell the following will log only the errors to a file:
```powershell
bonsai --no-editor workflow.bonsai 2>> log.file
``` 
Fixes #1410
=> Redirect headless exceptions to stderr

Bonsai.Configuration/ScriptExtensions.cs
This PR adds an assembly reference for `System.Runtime.Serialization` containing data contract serializer types.
=> Add assembly reference for data serialization

Bonsai.Shaders.Design/Bonsai.Shaders.Design.csproj, Bonsai.Shaders/Bonsai.Shaders.csproj, Bonsai.Shaders/LoadImage.cs
To avoid inconsistent access to shared state, this PR now clones the image configuration prior to the asynchronous call to load and upload the buffer to the GL texture memory.
This will allow dynamic modifications to any properties of the `LoadImage` operator as long as they are done synchronously with notifications coming from the input source sequence.
Fixes #1417
=> Cache configuration parameters for each async call in LoadImage operator

Bonsai.NuGet/Bonsai.NuGet.csproj
This PR updates the NuGet protocol version to address the dependabot security advisory:
https://github.com/bonsai-rx/bonsai/security/dependabot/2
=> Bump NuGet.Protocol from 6.3.1 to 6.6.1

Bonsai.Dsp.Design/Bonsai.Dsp.Design.csproj, Bonsai.Dsp.Design/WaveformView.cs, Bonsai.Dsp/Bonsai.Dsp.csproj
Changing the history length of the buffered visualizers for high-frequency waveforms is a common operation for monitoring signals over longer time periods. The only way to do it interactively is currently through the UI of the `MatVisualizer`, by right-clicking the window to bring up the status bar, then selecting a small arrow drop-down at the bottom-right corner and changing a number by hand in a text box.
This PR simplifies this operation by introducing a keyboard shortcut (`Ctrl + Plus` and `Ctrl + Minus` respectively) to step up and down history length by 1. Holding `Ctrl + Shift + Plus` or `Ctrl + Shift + Minus` will increase/decrease the history length by 10.
=> Add keyboard shortcut for changing history length

Bonsai.System/IO/FileSink.cs
`FileSink` writers are used when file creation needs to be deferred until the first element of the observable sequence is provided (e.g. if opening the writer requires knowing the size of a video frame).
Previously, all checks on file name were deferred until this moment. However, for improved consistency with support for early binding of file name provided by #1377, this PR moves most of the checks earlier in the observable lifetime, so that it does not become necessary to wait until a value is finally produced to detect an error in the specified file name. For example, the arrival of the first element can take several hours for infrequent events and can be frustrating to find out only at that time that we forgot to provide a non-empty file name.
=> Early error checking and file name generation for FileSink

Bonsai.Design.Visualizers/BarGraphVisualizer.cs, Bonsai.Design.Visualizers/Bonsai.Design.Visualizers.csproj, Bonsai.Design.Visualizers/BufferedVisualizer.cs, Bonsai.Design.Visualizers/GraphHelper.cs, Bonsai.Design.Visualizers/LineGraphVisualizer.cs, Bonsai.Design.Visualizers/RollingGraphBuilder.cs, Bonsai.Design.Visualizers/RollingGraphVisualizer.cs, Bonsai.Design.Visualizers/TimeSeriesVisualizer.cs, Bonsai.Design.Visualizers/TimestampedTimeSeriesVisualizer.cs
This PR introduces a new abstract visualizer class for automatically buffering value updates. This significantly reduces the number of updates to the UI thread coming from high-frequency visualizers, which also prevents crashing X11 services on the cross-platform Linux editor.
All values are still timestamped in the original notification thread before being buffered. The new backwards-compatible virtual call allows access to the original timestamps where needed.
=> Improve support for high-frequency visualizers

Bonsai.Editor/EditorForm.cs, Bonsai.Editor/GraphView/AnnotationPanel.cs
The WebView2 control is significantly costly to initialize as it relies on full-blown chromium. Since each of the workflow editor windows may have one of these, it is best to delay the complete initialization call for when the annotation panel actually loads to make for a smoother editor startup experience.
=> Allow lazy initialization of webview panel

Bonsai.Core/Expressions/AsyncSubjectBuilder.cs, Bonsai.Core/Expressions/BehaviorSubjectBuilder.cs, Bonsai.Core/Expressions/PublishSubjectBuilder.cs, Bonsai.Core/Expressions/ReplaySubjectBuilder.cs, Bonsai.Core/Expressions/ResourceSubjectBuilder.cs, Bonsai.Core/Expressions/SubjectExpressionBuilder.cs, Bonsai.Core/Expressions/SubscribeSubject.cs, Bonsai.Core/Expressions/VisualizerMappingBuilder.cs, Bonsai.Core/Expressions/WorkflowInputBuilder.cs, Bonsai.Core/Reactive/Subjects/AsyncSubject.cs, Bonsai.Core/Reactive/Subjects/BehaviorSubject.cs, Bonsai.Core/Reactive/Subjects/PublishSubject.cs, Bonsai.Core/Reactive/Subjects/ReplaySubject.cs, Bonsai.Core/Reactive/Subjects/ResourceSubject.cs, Bonsai.Editor/GraphModel/ElementIcon.cs, Bonsai.Vision/Bonsai.Vision.csproj, Bonsai.Vision/CameraCapture.cs, Bonsai.Vision/FileCapture.cs, Bonsai.Vision/VideoWriter.cs
This PR unifies the qualified name syntax for workflow element icons between `WorkflowElementIcon` and `WorkflowNamespaceIcon` attributes. The qualified name can now be prefixed with the assembly name in both cases.
The resource qualifier may also be omitted either when providing an assembly name or when an icon matching the full name of the type is already provided by the editor assembly.
=> Simplify qualified name for workflow element icons

Bonsai.System/IO/Ports/PortNameConverter.cs, Bonsai.System/Resources/ResourceNameConverter.cs
The base abstract resource name converter class is modified to filter out resources which are declared inside disabled nodes. This avoids listing in the converter drop-down any resources that will not be available at runtime.
Fixes #1438
=> Avoid returning resources declared inside disabled nodes

Bonsai.Templates/Bonsai.PackageTemplate/launchSettings.json
This PR updates the default debugger launch settings in the package project template to make it easier to debug custom packages against the new bootstrapper. The main difference from the previous settings is enabling the native debugger, which is now required for attaching breakpoints to the child processes initiated by the bootstrapper. Child processes are now used instead of managed AppDomain instances to improve the cross-platform experience and to start migrating into the new .NET Core world which does not allow for multiple AppDomain instances at all.
Fixes #1402
=> Update package template debug settings for new bootstrapper

Bonsai.System/IO/Ports/ObservableSerialPort.cs, Bonsai.System/IO/Ports/SerialPortDisposable.cs, Bonsai.System/IO/Ports/SerialPortManager.cs
This PR resolves concurrency issues around dynamic disposal of serial port connections, especially involving contention and locking inside reactive combinators. The current implementation relies on shared locking of the base stream to implement at-least-once semantics for closing the serial port.
It is unfortunately not ideal in that it does not completely guarantee synchronous disposal of the resource. To do this for all edge-cases would require reimplementing the callback logic in the `SerialPort` class or reimplement the serial port observable using polling via a dedicated service thread.
Fixes #1437
=> Avoid deadlock when disposing serial connection

.git-blame-ignore-revs, Bonsai.Arduino/AnalogInput.cs, Bonsai.Arduino/AnalogInputReceivedEventArgs.cs, Bonsai.Arduino/AnalogOutput.cs, Bonsai.Arduino/Arduino.cs, Bonsai.Arduino/ArduinoConfiguration.cs, Bonsai.Arduino/ArduinoConfigurationCollection.cs, Bonsai.Arduino/ArduinoDisposable.cs, Bonsai.Arduino/ArduinoManager.cs, Bonsai.Arduino/Bonsai.Arduino.csproj, Bonsai.Arduino/CreateArduino.cs, Bonsai.Arduino/DigitalInput.cs, Bonsai.Arduino/DigitalInputReceivedEventArgs.cs, Bonsai.Arduino/DigitalOutput.cs, Bonsai.Arduino/InputPullUp.cs, Bonsai.Arduino/ObservableArduino.cs, Bonsai.Arduino/PortNameConverter.cs, Bonsai.Arduino/Properties/AssemblyInfo.cs, Bonsai.Arduino/Properties/launchSettings.json, Bonsai.Arduino/ReceiveSysex.cs, Bonsai.Arduino/SendSysex.cs, Bonsai.Arduino/ServoOutput.cs, Bonsai.Arduino/SysexReceivedEventArgs.cs, Bonsai.StarterPack/Bonsai.StarterPack.csproj, Bonsai.sln
The Arduino package provided an implementation of the Firmata protocol over serial port using the `DataReceived` event. Similar to https://github.com/bonsai-rx/bonsai/pull/1444 this PR refactors the package implementation to avoid relying on events, both for cross-platform compatibility and for cleaner dispose logic.
For release simplicity, the package was temporarily merged back into the core repository, but the goal remains to split it off into its own separate repo.
=> Refactor arduino interface to avoid event callback

Bonsai.Design/BufferedVisualizer.cs, Bonsai.Design/ObjectTextVisualizer.cs
Since the default text visualizer has the broadest compatibility with all data types, it is increasingly used to inspect all kinds of data including high-throughput event streams. Unfortunately, this can place a high load on visualizers and cause stalls by refreshing complex text boxes at a high frequency.
This PR refactors the default text visualizer to use buffered updates. It also extends the default buffered visualizer interface to allow having a single control refresh per buffer and configurable target update interval.
=> Refactor text visualizer to use buffered updates

Bonsai.Configuration/Bonsai.Configuration.csproj, Bonsai.Configuration/ConfigurationHelper.cs, Bonsai.Configuration/ScriptExtensionsProvider.cs, Bonsai.NuGet/Bonsai.NuGet.csproj, Bonsai.Player/Bonsai.Player.csproj
This PR allows the player project to run as a command-line application on .NET 6.0 platforms. Extension scripts are not currently supported in .NET 6 as this would require porting over the Roslyn infrastructure. We will address this in a future release when we extend Roslyn support to all scripts.
=> Add net6.0 build target to player project

Bonsai.Audio/Bonsai.Audio.csproj, Bonsai.Core.Tests/Bonsai.Core.Tests.csproj, Bonsai.Core/Bonsai.Core.csproj, Bonsai.Dsp/Bonsai.Dsp.csproj, Bonsai.Editor.Tests/Bonsai.Editor.Tests.csproj, Bonsai.Editor/Bonsai.Editor.csproj, Bonsai.NuGet/Bonsai.NuGet.csproj, Bonsai.Shaders/Bonsai.Shaders.csproj, Bonsai.System.Tests/Bonsai.System.Tests.csproj, Bonsai.Vision/Bonsai.Vision.csproj, Bonsai32/Properties/launchSettings.json
This PR updates all common package dependencies to their latest versions:
- Editor dependencies
- Unit test dependencies
- Rx (updated to latest v6.0 for lightweight .NET 6.0 support)
- OpenCV.NET (now includes mono DLL map config file for cross-platform runtimes)
=> Update package dependencies

Bonsai.Audio/Bonsai.Audio.csproj, Bonsai.Scripting/Bonsai.Scripting.csproj, Bonsai.System.Design/Bonsai.System.Design.csproj, Bonsai.System.Tests/Bonsai.System.Tests.csproj, Bonsai.Templates/Bonsai.SourceTemplate/.template.config/template.json, Bonsai.Templates/Bonsai.Templates.csproj, Bonsai.Vision.Design/Bonsai.Vision.Design.csproj
This PR adds a new item template for sources using `dotnet new`. It leverages the new binding support introduced in .NET 7.0 SDK to extract the current project root namespace.
Example usage: `dotnet new bonsaisource -n MySource`
=> Add source item template for dotnet new

Bonsai.Core/Expressions/ExternalizedDateTimeOffset.cs, Bonsai.Core/Expressions/ExternalizedTimeSpan.cs, Bonsai.Core/Expressions/Properties/DateTimeOffsetProperty.cs, Bonsai.Core/Expressions/Properties/TimeSpanProperty.cs, Bonsai.Core/Expressions/ReplaySubjectBuilder.cs, Bonsai.Core/Reactive/BufferTime.cs, Bonsai.Core/Reactive/BufferTrigger.cs, Bonsai.Core/Reactive/Concurrency/SchedulerMapping.cs, Bonsai.Core/Reactive/Delay.cs, Bonsai.Core/Reactive/DelaySubscription.cs, Bonsai.Core/Reactive/Gate.cs, Bonsai.Core/Reactive/GateInterval.cs, Bonsai.Core/Reactive/Replay.cs, Bonsai.Core/Reactive/SampleInterval.cs, Bonsai.Core/Reactive/Subjects/ReplaySubject.cs, Bonsai.Core/Reactive/Throttle.cs, Bonsai.Core/Reactive/TimedGate.cs, Bonsai.Core/Reactive/Timeout.cs, Bonsai.Core/Reactive/Timer.cs, Bonsai.Core/Reactive/WindowTime.cs, Bonsai.Core/Reactive/WindowTrigger.cs, Bonsai.Dsp/FirFilter.cs, Bonsai.Dsp/IirFilter.cs, Bonsai.Shaders/Delay.cs, Bonsai.Shaders/DelaySubscription.cs, Bonsai.Shaders/Timer.cs, Bonsai.Vision/Drawing/AddTextBase.cs, Bonsai.Vision/Drawing/CreateFont.cs, Bonsai.Vision/Filter2D.cs, Bonsai.Vision/WarpAffine.cs
This PR hides all XML serialization properties from the public API. These properties are an implementation detail of how XML serialization currently works and might change at any point so we want to make it clear that they shouldn't be relied upon.
Fixes #1205
=> Remove XML serialization properties from public API

Bonsai.Core.Tests/OverloadedCombinatorBuilderTests.cs, Bonsai.Core/Expressions/ExpressionBuilder.cs
This PR implements an additional tie-break for ambiguous overload resolution where, all else being equal, applicable overloads provided by a derived class are preferred to overloads provided by the base class.
According to the [C# specs for signature scoping](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/basic-concepts#7722-hiding-through-nesting), for the purposes of this tie-break we should consider the declaring type of a virtual method to be the base definition, ignoring any overrides.
Fixes #1054
=> Add tie-break for method overloads in derived classes

Bonsai.Editor/GraphModel/GraphNode.cs, Bonsai.Editor/GraphView/GraphViewControl.cs
Currently the editor visual annotation for obsolete operators is competing with that for disabled operators. Both drop the category color associated with the original node. This PR improves the amount of visual information provided for obsolete operators by preserving the original category color.
It also makes it possible to distinguish between disabled obsolete operators and disabled normal operators, since disabled obsolete operators will now visibly change from colored to gray, but keep the distinctive foreground hatch pattern.
=> Improve information contrast for obsolete operators

Bonsai.System/IO/Ports/ObservableSerialPort.cs, Bonsai.System/IO/Ports/SerialRead.cs
This PR adds support for continuous streaming of fixed size buffers from the low-level `SerialRead` operator. This makes `SerialRead` work symmetrically with the `SerialReadLine` operator. Furthermore we adapted the triggered interface to use the `Read` methods from serial port for parity with `SerialReadLine` usage and to allow for interleaving binary and text operators.
Care should be taken to ensure that the binary stream is correctly aligned. Cancellation of blocking operations is supported but the serial port will not be closed until the corresponding subscription to `CreateSerialPort` is cancelled, or all operators accessing the serial port are cancelled.
=> Add support for streaming binary serial read buffers

Bonsai.Vision/Normalize.cs
Fixes #1399 .
The current version of `Normalize` implements ConvertScale with `shift` in "raw", unscaled, units.
https://github.com/bonsai-rx/bonsai/blob/404b092b501fbd9a0db5ccce76bf695623e6ba7c/Bonsai.Vision/Normalize.cs#LL34C17-L34C32
```csharp
var range = max - min;
var scale = range > 0 ? 1.0 / range : 0;
var shift = range > 0 ? -min : 0;
CV.ConvertScale(input, output, scale, shift);
```
However, the [native function from opencv](https://docs.opencv.org/3.4/d2/df8/group__core__c.html#ga3a6c66666ac8c30f639c85dd18df9f67) seems to follow algebraic order of operations (i.e. Multiplication -> Addition), resulting in applying the scaling first and the shift second.
It seems the easiest way to correct this would be to normalize the shift by the range:
```csharp
var shift = range > 0 ? …
```
=> Ensure output of Normalize is bounded between zero and one

Bonsai.Core.Tests/CombinatorBuilderTests.cs, Bonsai.Core.Tests/OverloadedCombinatorBuilderTests.cs, Bonsai.Core.Tests/SubjectTests.cs, Bonsai.Core.Tests/TypeConversionTests.cs, Bonsai.Core/Expressions/MulticastSubject.cs
The implementation of `MulticastSubject` performed a coercion of the source sequence when the type of values in the sequence did not directly match the type of the subject. This PR makes this behavior more strict: conversions are still allowed, but they have to be supported on type upcasting, interface implementation, or a user-defined explicit conversion between the two types.
This eliminates cases where the type of the source sequence is an interface being multicast to a subject type declared with a different interface.
Fixes #1458
=> Require user defined conversion when multicasting to subject with non-matching type

Bonsai.Dsp.Design/MatVisualizer.cs, Bonsai.Dsp.Design/SpikeWaveformCollectionVisualizer.cs
High-sampling rate visualizers were some of the first visualizers in the language to be buffered. This PR unifies this buffering strategy using the new `BufferedVisualizer` abstract base class. The main difference is the built-in protection against overloading the window message loop in case of high-frequency notifications (e.g. small buffers emitted at high-frequency).
=> Refactor matrix and spike visualizers to use buffered updates

Bonsai.Design/FolderBrowserDialog.cs, Bonsai.Design/FolderNameEditor.cs, Bonsai.Editor/StartScreen.Designer.cs, Bonsai.Editor/StartScreen.cs, Bonsai.Editor/StartScreen.resx, Bonsai/Program.cs
This PR adds support for opening the IDE on a specific folder, which can be passed either as an argument to the command-line or selected in the start screen. The main use for this functionality is to allow starting a new workflow using extensions available on an existing project folder, without requiring opening an existing workflow.
To make it easier to use existing local environments, the open dialogs also now use the path to the most recent file as a starting location.
=> Allow starting editor session on a specified folder

Bonsai.Vision/VideoWriter.cs, Bonsai.Vision/VideoWriterDisposable.cs
This PR resolves a subtle issue with `VideoWriter` parallelism where the frame size of the writer was cached at the class level. The cache has now been moved to the per-subscription disposable instance, ensuring that multiple subscriptions can be safely created over the same operator.
Fixes #1467
=> Ensure VideoWriter frame size is cached per subscription

Bonsai.Design/ObjectTextVisualizer.cs
This PR ensures the default text visualizer always displays a single row for every element in a sequence, even if the string representation of the object includes line break characters. This is important to ensure the correctness of the visualizer behavior: expanding the height of the visualizer window directly controls how many values are buffered on the display by using multiples of the rendered line height.
If arbitrary multi-line text is left to render unfiltered, this calculation has the potential to be thrown off in a very misleading way, as expanding the control to see all the lines will have the effect of expanding the buffer. Since in this case a single value would already fill up multiple lines, and new values are shown at the bottom, this would mean that the value at the top …
=> Ensure single row display for text visualizer

Bonsai.Editor/GraphView/GraphViewControl.cs
Similar to multi-line text editors, this PR updates the editor to move the cursor to the end of the line when clicking in the empty space to the right of the last node. It also moves the cursor to the last node when clicking in the empty space below the last line.
=> Improve cursor selection when clicking in editor empty space

Bonsai.Editor/EditorForm.cs
This PR ensures that editor bounds restored from user settings can be visible at least in one of the connected screens. The approach chosen is to test whether the bounds intersect at least one of the available screens. This was preferred to a strict "contains" test to avoid resetting the settings when only a few pixels are outside the working area.
Fixes #1281
=> Ensure restored bounds are at least in one screen

Bonsai.Design/ObjectTextVisualizer.cs, Bonsai.Design/RichTextLabel.cs
During high-frequency text visualizer updates on Mono, the caret is redrawn at the update frequency of the text box control. This PR disables caret selection entirely for a more streamlined and performant visualization experience.
The only disadvantage is that the possibility of copy / pasting text from the control is also disabled, but this is a feature which is very hard to use for scrolling streams anyway as the selection is constantly invalidated by new updates.
=> Disable caret selection from text visualizer

Bonsai.Design/ObjectTextVisualizer.cs, Bonsai.Design/RichTextLabel.cs
The default text visualizer is commonly used to inspect the running state of arbitrary sequences throughout the workflow. When a running stream may output several identical values, it can be hard to distinguish whether the sequence has stopped or is emitting constantly identical values.
This PR makes this easier by providing a new action (mouse button right double-click) that clears the text visualizer.
=> Clear text visualizer on right double-click

Bonsai.System/IO/ReadAllText.cs, Bonsai.System/IO/WriteAllText.cs
This PR adds support for `ReadAllText` and `WriteAllText` operators, mirroring the .NET framework equivalent helpers with the same name. The goal is to provide quick interfacing to reading and writing entire contents of text files, e.g. for serialization/deserialization purposes.
In the future we will want to generalize the IO streaming interface, but in the meantime these can provide a flexible compromise, for example for small config files.
=> Add ReadAllText and WriteAllText operators

Bonsai.Core/Expressions/InputMappingBuilder.cs, Bonsai.Core/Expressions/MemberSelectorBuilder.cs, Bonsai.Core/Expressions/TypeMapping.cs, Bonsai.Core/Expressions/TypeMappingConverter.cs, Bonsai.Core/Expressions/VisualizerMappingBuilder.cs
Allow properties exposing an abstract `TypeMapping` type to provide standard values in the type converter when the hosting context declares allowable extension types with the [`XmlIncludeAttribute`](https://learn.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmlincludeattribute). This makes it easier to generate builder operators requiring type hinting, such as deserializers of data contracts, schemas, etc.
=> Allow TypeMapping extension types

Bonsai.System.Design/Resources/CollectionEditor.cs
The `CollectionEditor` provides a default automatic way of looking for derived types based on `XmlIncludeAttribute` annotations. This PR makes this automatic search more flexible by allowing types to be filtered by visibility using the [`DesignTimeVisibleAttribute`](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.designtimevisibleattribute). Types marked with the `Visible` property set to `false` will not be included in the list of new item types.
=> Allow filtering which types to include in CollectionEditor

Bonsai.Configuration/Bonsai.Configuration.csproj, Bonsai.Configuration/ConfigurationHelper.cs, Bonsai.Configuration/NativeMethods.cs, Bonsai.Player/Bonsai.Player.csproj, Bonsai/Bonsai.csproj
Starting from Windows 8 and Windows 7 SP1 KB2533623, [Microsoft introduced new API enhancements for securely loading external native libraries](https://support.microsoft.com/en-us/topic/microsoft-security-advisory-insecure-library-loading-could-allow-remote-code-execution-486ea436-2d47-27e5-6cb9-26ab7230c704).
The new API defines a process wide DLL search path which is modified only by direct calls to OS-specific functions. Modern .NET libraries that declare the [`DefaultDllImportSearchPath`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.defaultdllimportsearchpathsattribute?view=netframework-4.7.2) attribute set to [`DllImportSearchPath.SafeDirectories`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportsearchpath?view=netfra …
=> Add library folders to DLL search path on windows

Bonsai/Program.cs
When assembling the string assigned to the `Arguments` property of `ProcessStartInfo` we must manually ensure that any arguments with spaces are surrounded by quotation marks (see [Remarks](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.arguments?view=net-7.0#remarks) for more details).
Fixes #1541
=> Ensure arguments with spaces are surrounded by quotation marks

Bonsai.Vision.Design/Bonsai.Vision.Design.csproj, Bonsai.Vision.Design/ImageEllipsePicker.cs, Bonsai.Vision.Design/IplImageCircleEditor.cs
This PR ensures that circle radius is correctly converted to ellipse width, and vice-versa, when setting up the graphical circle picker. We also fixed a minor issue where the circle was being edited as an ellipse during the resize operation.
Fixes #1620
=> Fix circle picker rescaling and size conversion issues

Bonsai.Vision/Bonsai.Vision.csproj, Bonsai.Vision/Circle.cs
This PR adds the missing constructor that allows creating dynamic values of type `Circle` without the need for custom scripting modules.
Fixes #1622
=> Add missing circle constructor

Bonsai.Configuration/Bonsai.Configuration.csproj, Bonsai.Configuration/ConsoleBootstrapper.cs, Bonsai.Player/Bonsai.Player.csproj, Bonsai/Bonsai.csproj, Bonsai32/Bonsai32.csproj
This PR updates the implementation of `RunPackageOperationAsync` in the console bootstrapper class to avoid explicit scheduling of exception continuations. Instead, a standard try-catch block on top of the async-await pattern is used to ensure task completion in case of successful termination.
Fixes #1687
=> Avoid cancellation exception on task completion

Bonsai.Editor.Tests/Bonsai.Editor.Tests.csproj, Bonsai.Editor.Tests/WordSeparationTests.cs, Bonsai.Editor/Bonsai.Editor.csproj, Bonsai.Editor/GraphView/GraphViewControl.cs, Bonsai.Editor/StringExtensions.cs
This PR updates word separation rules for the editor graph view to improve the rendering of typical casing rules which might be used in operator names. In general all previous rules were preserved, and a few new ones added:
- Separators and punctuation marks are now explicit word separators
- Changes in casing either lower to upper, or upper to lower, are used to delimit word tokens. Non-letter characters are ignored and only the immediately preceding and subsequent characters are inspected. 
Fixes #1692
=> Improve detection of word boundaries in node names

Bonsai.Editor/EditorForm.cs
This PR caches the modifier key before initiating asynchronous calls to fetch documentation map. Apparently the async call can reset the modifier state even if the key is held. The second time it worked because HTTP call is cached.
Fixes #1653
=> Ensure external browser docs are shown on modifier

Bonsai.Configuration/NativeMethods.cs, Bonsai.Configuration/ScriptExtensions.cs, Bonsai.Editor.Tests/EditorHelper.cs, Bonsai.Editor.Tests/NestedSubscribeSubjectWithClosestRedefinition.bonsai, Bonsai.Editor.Tests/WorkflowEditorDefinitionTests.cs, Bonsai.Editor.Tests/WorkflowEditorTests.cs, Bonsai.Editor/ExportHelper.cs, Bonsai.Editor/GraphModel/WorkflowBuilderExtensions.cs, Bonsai/ScriptExtensionsEnvironment.cs
This PR fixes the search command for retrieving subject definitions in the case of subject redefinition. In this case subject definitions with the same name will appear in multiple locations along the call context stack. Previously we were looking for the last definition, however because the search data structure is a LIFO the closest definition is actually the first definition at the top of the stack.
Fixes #1586
=> Ensure retrieval of closest subject definition

Bonsai.NuGet.Design/Bonsai.NuGet.Design.csproj, Bonsai.NuGet.Design/PackageViewController.cs, Bonsai.NuGet/Bonsai.NuGet.csproj, Bonsai.NuGet/QueryHelper.cs, Bonsai.NuGet/SearchQuery.cs, Bonsai.NuGet/SourceRepositoryExtensions.cs, Bonsai.NuGet/UpdateQuery.cs
This PR enables filtering the local package repository prior to querying for package updates. It also runs all update queries in parallel, resulting in significant performance improvements for nuget.org update queries.
Fixes #1524
=> Allow filtering package updates

Bonsai.Core/Expressions/InspectBuilder.cs
Currently type visualizers are associated with either data types or operator types. Operator-type specific visualizers are automatically propagated through subject nodes, disabled nodes or empty group nodes, but not within any other reactive operators.
This PR extends this implicit propagation specifically to `Sink` group nodes. `Sink` nodes implicitly create an internal subject to allow their nested logic to be handled without changing the original sequence. Implicit propagation of visualizer assignments through `Sink` nodes would allow for example simple transformation of GUI element notifications before multicasting the data through subjects elsewhere in the workflow.
Fixes #1742
=> Preserve visualizer types across nested sink nodes

Bonsai.Core/Expressions/CombinatorBuilder.cs
Operator properties can sometimes represent shared state which is meant to be assigned and used only at runtime, and which needs to be explicitly invalidated in between workflow execution (see #1083).
Such operators can use the `ResetCombinatorAttribute` to indicate they want any non-serializable properties (i.e. properties marked with the `XmlIgnoreAttribute`) to be reset to their default values on every build. Currently this is implemented as a delegate which is emitted at build time for every resettable operator. However, since the delegate logic depends only on the combinator type, it would be possible to cache the emitted delegates to avoid re-emitting delegates for multiple uses of the same operator.
This PR introduces a nested generic type to serve as the cache, which should speed …
=> Avoid rebuilding combinator reset delegate

Bonsai.Editor/WorkflowRunner.cs
(Submitted as a draft since I want to double-check some things tomorrow morning and probably revisit the wording in the explanation comment.)
This issue was actually two different issues in a trench coat:
---------------------
For a completely empty workflow (and perhaps other simple workflows?) the finally action will execute on the main thread, which causes `Application.Exit` to be called before `Application.Run` which means it doesn't exit.
---------------------
The second scenario is a workflow that end naturally and has a visualizer enabled. ([Example workflow](https://github.com/bonsai-rx/bonsai/files/15083579/take10.zip))
In this case the finally action will execute on a background thread. `Application.Exit` invokes `FormClosing` and `FormClosed` event handlers directly. This means …
=> Fix workflows run from the command line not exiting upon completion

.editorconfig, Bonsai.Configuration/ScriptExtensions.cs, Bonsai.Configuration/ScriptExtensionsProjectMetadata.cs, Bonsai.Configuration/ScriptExtensionsProvider.cs, Bonsai/DependencyInspector.cs
The setting can be toggled by modifying `Extensions.csproj`, same as any other C# project.
This change also improves the robustness of the `UseWindowsForms` check since I modified it to use the helper I added for this change.
In particular it now only checks in appropriate locations within the project file, and perhaps more importantly it disregards the case of `true` vs `True`. At some point\* Visual Studio started using the latter when these settings are changed via the UI, so anyone using it would've had `True` treated as false.
<sub>(\*I assume so at least, I typically just modify my `csproj` by hand and I don't have an old version of Visual Studio to check at the moment–I would guess it changed when they redid the project configuration tool.)</sub>
Opening the whole project file to …
=> Allow script extensions to declare unsafe blocks

Bonsai.Editor/EditorForm.cs
The current check for deciding whether a toolbox node can be dragged into the workflow was based on testing for number of children, i.e. operator nodes are always leaf nodes either in hierarchical or search mode.
However, category nodes can also be leaf nodes if there are no operators of that category. This can easily happen for the `Workflow` and `Subject` categories. An additional restriction to prevent this is to check whether the node actually has a non-null content `Tag`.
Fixes #1759
=> Prevent empty category nodes from being dragged into the workflow

Bonsai.Core/ObservableCombinators.cs, Bonsai.Core/Reactive/GateInterval.cs
This was caused by a change from the `Observable.Window(Func<IObservable<>> windowClosingSelector)` overload to the `Observable.Window(IObservable<> windowBoundaries)` overload done in https://github.com/bonsai-rx/bonsai/commit/606d6feed4932876df231b867c150db072a1c828 for https://github.com/bonsai-rx/bonsai/pull/1315
These two overloads don't actually act quite the same way:
* The former calls the function to retrieve an observable and subscribes to it every time a window opens. The window will close once it emits an element.
* The latter subscribes once and the timing of elements emitted by the sequence determines when the window will close then re-open again.
The observable returned by [`Observable.Timer`](https://reactivex.io/documentation/operators/timer.html) implicitly resets when …
=> Fix GateInterval not working after the first tick

Bonsai.Dsp/FirFilter.cs
The underlying implementation of the `FirFilter` operator uses the [`filter2D`](https://docs.opencv.org/4.x/d4/d86/group__imgproc__filter.html#ga27c049795ce870216ddfb366086b5a04) function from OpenCV to efficiently apply the filter.
Although the documentation of `filter2D` itself states that it "convolves an image with a kernel", in fact the implementation actually computes the cross-correlation. This is a surprisingly common, if misleading, assumption in the computer vision and image processing field, likely coming from the use of either symmetric kernels (in which case correlation is equal to convolution), or learned kernels (in which case the learning process can easily deal with reversed kernel weights).
Nevertheless, the current reference documentation of the operator can be …
=> Clarify use of cross-correlation for FIR filters

Bonsai.Editor/DocumentationException.cs, Bonsai.Editor/DocumentationHelper.cs, Bonsai.Editor/EditorForm.cs
The deserialization exceptions were making it to the generic unhandled exception dialog due to the relevant catch clause looking for `SystemException`.
`SystemException` (and its complement `ApplicationException`) is a bit of a failed experiment from .NET Framework 1. It's no longer used for new `System.*` exceptions, and even before .NET Core it was applied very inconsistently. IMO the line between exceptions in the `System` namespace and exceptions outside of it is basically meaningless and very fuzzy regardless.
As such this PR increases the scope to just plain `Exception`.
------------------
This still would have resulted in very vague low-level errors reaching the end user, so I introduced `DocumentationException` to denote specific errors when parsing the XRefMap.
When one XRefMap …
=> Fixed uncaught exception when XRefMap is invalid

Bonsai.Editor/DocumentationHelper.cs
With today's Bonsai documentation, the GZip-compressed XRefMap is only 200 KB. That's down from 2.74 MB uncompressed 🎉
The TODO is so we hopefully remember to switch to `DecompressionMethods.All` when we upgrade to modern .NET so that we can take advantage of Brotli and any other future compression methods supported in the future.
(Gonçalo and I considered manually using [`~DecompressionMethods.None`](https://github.com/dotnet/runtime/blob/56d7e5d80ed6dd5e80ca8225ab689a60cae3cfc7/src/libraries/System.Net.Primitives/src/System/Net/DecompressionMethods.cs#L13) since it works downlevel, but decided this might be confusing.)
=> Enable support for compressed XRefMap from documentation server

Bonsai.Configuration/ConsoleBootstrapper.cs
This PR modifies the console bootstrapper behavior to ensure the full exception stack trace is dumped to the logger in the event of an error. The motivation is to improve the debugging experience in terminal-only environments where visualization and exploring of networking and authentication issues may be complicated.
The original bug report suggested throwing at the top-level application, but this may have knock-on effects on the inter-process communication underlying the bootstrapper logic and when calling the Bonsai process from other applications, so it is avoided by having a more verbose log behavior at the level of the specific bootstrapper.
Fixes #1804
=> Log full exception trace for console bootstrap

Bonsai.Editor/Layout/LayoutHelper.cs
This is potentially not the most elegant solution possible here, but Gonçalo asked me to take a quick look and see if we could squeeze a fix in for 2.8.3.
Maybe this is good enough to just prevent the crash since we don't expect anyone to actually intentionally make graphs like this and this code only runs on startup. If not we could leave https://github.com/bonsai-rx/bonsai/issues/1769 open and do a more thorough investigation later.
I'm not attached to the wording of the message if anyone has a better suggestion. (Might be more accurate to say the same node appears multiple times in the mashup? Not sure if people would actually consider `VisualizerMapping` associations to be mashups though, that feels like internal nomenclature leaking to the surface.)
For some reason the error dialog …
=> Prevent infinite recursion when visualizer mappings of the same node are combined together

Bonsai.Editor/SemanticVersion.cs
Not important for 2.8.3. The official release builds don't have build meadata so this doesn't affect them.
----------
Bonsai has randomly been telling me that it has "upgraded" workflows I literally just saved. I finally got annoyed enough to poke around to figure out why it thought my workflow was upgraded.
Turns out it was "upgrading" them because the `version` was null here, causing the check to always succeed:
https://github.com/bonsai-rx/bonsai/blob/88a2412f25c467a1ef3505477413900484518e49/Bonsai.Editor/GraphModel/UpgradeHelper.cs#L229-L231
It was null because the parsing in `SemanticVersion` was not handling the build metadata. This change properly ignores it per the semver spec.
I considered adding a `BuildMetadata` property to `SemanticVersion`, but I felt it wasn't super valuable …
=> Fix build metadata in workflow version causing semver parsing to fail

.github/workflows/Bonsai.yml, .github/workflows/create-build-matrix.py
Minor change to release automation I realized should be done after I saw your fork as failing CI.
Forks won't always have the `latest` tag (and even if they do it might be stale), so don't bother with package comparison unless the fork explicitly enables it.
⚠ Before merging you need to [add an Actions variable](https://github.com/bonsai-rx/bonsai/settings/variables/actions) `ENABLE_PACKAGE_COMPARISON` = `true` to this repo.
(Forks can also choose to define that variable to assert that their `latest` tag is valid and that they want the comparisons done.)
=> Make package comparison in CI optional for the sake of forks

Bonsai.Configuration/ConsoleBootstrapper.cs, Bonsai/Program.cs
During release automation development we realized that unhandled exceptions in the bootstrapper might still be swallowed by the main process, e.g. due to assembly resolution failures. This was fixed in #1873 but with the side-effect that multiple exception traces would now be printed for console bootstrapper package resolution errors, since exceptions were also being routed and printed by the internal bootstrapper console logger.
This PR simplifies error handling to let all exceptions from the console bootstrapper surface naturally, while simultaneously preventing stack trace complexity by flattening the most common case where the `AggregateException` contains a single inner exception.
Fixes #1804
=> Log all unhandled bootstrapper exceptions

Bonsai/Bonsai.csproj
Another minor echo of the release automation changes.
This hides the DLLs embedded in the bootstrapper for `System.Resources.Extensions` and its dependencies from the solution explorer, which are unintentionally left visible before this change:
These don't live in the project folder, and without the context of reading the csproj they're just confusing noise.
(That being said if you like being reminded that they're there we can just leave them. Could also hide them in a folder as an in-between option.)
Relates to https://github.com/bonsai-rx/bonsai/pull/1873
=> Hide embedded DLLs from the solution explorer

Bonsai.Design/ObjectTextVisualizer.cs
There also existed an edge case where `bufferSize` was 0 if the visualizer never got painted.
Fixes https://github.com/bonsai-rx/bonsai/issues/1875
Supersedes https://github.com/bonsai-rx/bonsai/pull/1876
=> Fix `ObjectTextVisualizer` allowing a buffer size of 0

Bonsai.Configuration/AssemblyLocationCollection.cs, Bonsai.Configuration/ConfigurationHelper.cs, Bonsai.Configuration/PackageConfigurationUpdater.cs
The local environment `.config` file has relied so far on OS-specific path strings to determine assembly locations and native library folders. However, because of this it is currently not possible to version `.config` files across platforms, e.g. Windows and Linux, since the direction of slashes is different.
This PR normalizes config file manipulations to prefer Unix paths for all package install, update and removal operations. To allow for the greatest backwards compatibility as well as OS-specific path strings passed through the CLI interface, the behavior of the `PackageConfiguration` and `ConfigurationHelper` classes was not modified. Instead, normalization was implemented via the `PackageConfigurationUpdater`, which is responsible for actually manipulating the serializable …
=> Use forward slashes for package configuration

Bonsai.Core/Expressions/IncludeWorkflowBuilder.cs, Bonsai.Core/WorkflowBuilder.cs
Include workflows are loaded lazily and on-demand during the workflow build step, which means extension type discovery is performed in step-fashion for a newly loaded workflow. This gradual type discovery has dramatic implications in performance as documented in #1680, and this was having a visible impact on editor loading times, especially for complex applications with large numbers of include workflows.
This PR aims to improve the performance by preloading all extension types from included workflows ahead of time. The serialization of workflow properties was also optimized to minimize the number of required serializer instances.
The preloading optimization is disabled during builds to avoid supra-linear costs when recursively loading included workflows with deeply nested self-repeating …
=> Preload all extension types from include workflows

Bonsai/Bonsai.csproj, Bonsai/SystemResourcesExtensionsSupport.cs
Also added copying the `NuGet.config` file to the repack output directory for ease of testing.
Fixes https://github.com/bonsai-rx/bonsai/issues/1901
=> Fix redundant assembly resolution resulting in duplicate assembly loading

Bonsai.Configuration/ConfigurationHelper.cs
The `AssemblyResolve` event may be called concurrently from different threads as described in #1903, so here we introduce a global assembly cache (no pun intended) to avoid duplication of dynamically loaded assemblies.
Fixes #1903
=> Ensure all resolved assemblies are unique

.github/workflows/compare-nuget-packages.py
This is for improving readability on the summary of the detect changed packages action.
=> Fix some lists in the NuGet package comparison log not being sorted

README.md
We briefly talked about this during the release automation merge party so if you're still interested here it is!
[![Download Bonsai](https://img.shields.io/nuget/v/Bonsai?style=flat-square&label=Download%20Bonsai&labelColor=5e616c&color=ec2227)](https://bonsai-rx.org/docs/articles/installation.html) [![CI Status](https://img.shields.io/github/actions/workflow/status/bonsai-rx/bonsai/Bonsai.yml?branch=main&style=flat-square&label=CI&labelColor=5e616c)](https://github.com/bonsai-rx/bonsai/actions) [![Discord Community](https://img.shields.io/discord/722881880122327101?style=flat-square&label=Discord&logo=discord&logoColor=white&labelColor=5e616c)](https://discord.gg/zUhuDcYuJH) [![GitHub Discussions](https://img.shields.io/github/discussions/bonsai-rx/bonsai?style=flat-square&logo=github&lab …
=> Add Discord and GitHub Discussions badges to the readme

.github/workflows/create-portable-zip.py
This was my intent from the start since I did something similar in Biohazrd, I just forgot to do it apparently. Sorry about that!
Fixes https://github.com/bonsai-rx/bonsai/issues/1911
=> Fix NuGet testing feed appearing in official releases

.editorconfig, Bonsai.Core/Dag/DirectedGraph.cs, Bonsai.Core/Reactive/Slice.cs
For some reason the order of arguments into the [`ArgumentOutOfRangeException`](https://learn.microsoft.com/en-us/dotnet/api/system.argumentoutofrangeexception.-ctor?view=net-8.0#system-argumentoutofrangeexception-ctor(system-string-system-string)) constructor was swapped in all instances of the call in the `DirectedGraph` class, most likely because it is the reverse order from the more common [`ArgumentException`](https://learn.microsoft.com/en-us/dotnet/api/system.argumentexception.-ctor?view=net-8.0#system-argumentexception-ctor(system-string-system-string)).
=> Fix exception constructor argument order

Bonsai.Core/WorkflowBuilder.cs, Bonsai.Editor/AboutBox.cs
To avoid cluttering official release version strings stored in workflow files and displayed in the About box, this PR drops source link build metadata from product version strings.
Fixes #1912
=> Drop version build metadata for official releases

Bonsai.Core.Tests/SubjectTests.cs, Bonsai.Core.Tests/TestWorkflow.cs, Bonsai.Core/Expressions/MulticastSubject.cs
In its current implementation, `MulticastSubject` would automatically cast the values of the source sequence into the subject type, which constitutes a fundamental violation of the contract for `Sink` operators.
This PR ensures that the conversion is applied only when raising notifications to the subject, and that otherwise the type and values of the original sequence are left untouched.
Fixes #1914
=> Ensure multicast subject preserves source type

Bonsai.Audio/Properties/launchSettings.json, Bonsai.Design.Visualizers/Properties/launchSettings.json, Bonsai.Dsp.Design/Properties/launchSettings.json, Bonsai.Dsp/Properties/launchSettings.json, Bonsai.Osc/Properties/launchSettings.json, Bonsai.Scripting.Expressions.Design/Properties/launchSettings.json, Bonsai.Scripting.Expressions/Properties/launchSettings.json, Bonsai.Shaders.Design/Properties/launchSettings.json, Bonsai.Shaders.Rendering/Properties/launchSettings.json, Bonsai.Shaders/Properties/launchSettings.json, Bonsai.System.Design/Properties/launchSettings.json, Bonsai.System/Properties/launchSettings.json, Bonsai.Vision.Design/Properties/launchSettings.json, Bonsai.Vision/Properties/launchSettings.json, Bonsai.Windows.Input/Properties/launchSettings.json, tooling/Common.props
A set of `launchSettings.json` files are used to debug projects in the context of the local bootstrapper build. Unfortunately these have a tendency to go stale as build configuration evolves. This PR attempts to centralize their configuration by leveraging the `Common.props` file and the ability to expand simple property macros in the contents of `launchSettings.json`.
It also updates other settings to ensure native debugging and support for folder paths with spaces.
Fixes #1920
=> Update launch settings to target artifacts folder

Bonsai.Audio/Bonsai.Audio.csproj, Bonsai.Core.Tests/Bonsai.Core.Tests.csproj, Bonsai.Core/Bonsai.Core.csproj, Bonsai.Design.Visualizers/Bonsai.Design.Visualizers.csproj, Bonsai.Design/Bonsai.Design.csproj, Bonsai.Dsp.Design/Bonsai.Dsp.Design.csproj, Bonsai.Dsp/Bonsai.Dsp.csproj, Bonsai.Osc/Bonsai.Osc.csproj, Bonsai.Scripting.Expressions.Design/Bonsai.Scripting.Expressions.Design.csproj, Bonsai.Scripting.Expressions/Bonsai.Scripting.Expressions.csproj, Bonsai.Shaders.Design/Bonsai.Shaders.Design.csproj, Bonsai.Shaders.Rendering/Bonsai.Shaders.Rendering.csproj, Bonsai.Shaders/Bonsai.Shaders.csproj, Bonsai.StarterPack/Bonsai.StarterPack.csproj, Bonsai.System.Design/Bonsai.System.Design.csproj, Bonsai.System.Tests/Bonsai.System.Tests.csproj, Bonsai.System/Bonsai.System.csproj, Bonsai.Vision.Design/Bonsai.Vision.Design.csproj, Bonsai.Vision/Bonsai.Vision.csproj, Bonsai.Windows.Input/Bonsai.Windows.Input.csproj
In preparation for modernizing the editor to run with the .NET Core stack there are a number of core dependencies which need to be upgraded or modified to run beyond .NET Framework. [jacobslusser/ScintillaNET](https://github.com/jacobslusser/ScintillaNET) was until now one of the big concerns, since the project has been stale for almost 6+ years.
Fortunately, [fernandreu/ScintillaNET](https://github.com/fernandreu/ScintillaNET) now provides a .NET 6.0 compatible fork with a published NuGet package and the source code updates seem to be in great shape. Even though it still only targets windows, the component has even been updated with a new `arm64` runtime, which is a welcome addition for possibly targeting Windows on ARM.
Since this fork only targets .NET 4.7.1 we took the chance to …
=> Update ScintillaNET to support modern .NET

Bonsai.Core.Tests/InspectBuilderTests.cs, Bonsai.Core.Tests/TestWorkflow.cs, Bonsai.Core/Expressions/InspectBuilder.cs, Bonsai.Core/Reactive/Defer.cs
Previous enhancements to visualizer propagation rules introduced in #917, #1751 and #1889 allow flexible reuse, modification and encapsulation of visualizers inside group workflows and across subject multicasting.
However, some patterns remain problematic to achieve without introducing additional subject declarations. Specifically, given an observable sequence where data is generated by interaction with a UI element, it is not currently easy to post-process the values in the sequence without either losing the assigned visualizer or introducing a temporary subject.
This PR allows propagation of the visualizer element associated with the nested output in `Defer` operators, which enables encapsulation of these more flexible constructions with subjects.
For example, by combining `Defer` with …
=> Allow propagation of Defer nested sequence visualizer

Bonsai.Editor/Bonsai.Editor.csproj, Bonsai.Editor/DocumentationHelper.cs, Bonsai.NuGet.Design/IconReader.cs, Bonsai.NuGet.Design/PackageViewController.cs
The `WebRequest` API has sadly been deprecated by the more performant `HttpClient` in modern .NET. As this API is also available in .NET Framework, this PR aligns the two code bases by replacing all instances of `WebRequest` with an alternative implementation using `HttpClient`.
There were two main uses of `WebRequest` in the current source code:
- Retrieving package icons in the package manager dialog
- Retrieve XRefMap YAML content for package docs
Each of these is addressed separately, as the reimplementation is quite specific for each case. An opportunity was taken to refactor package icon retrieval away from UI code to improve separation of concerns.
Fixes #1936
=> Replace uses of WebRequest with HttpClient

Bonsai.Core/Reactive/CombineTimestamp.cs, Bonsai.Core/Reactive/CreateTimestamped.cs
The `CombineTimestamp` operator was introduced in one of the earliest releases of the language as a way to create timestamped values dynamically from pairs of values and timestamps. As a consequence of this early development, the naming of this operator does not follow current naming conventions.
This PR refactors `CombineTimestamp` into the new `CreateTimestamped` operator, for consistency with other creation operators and with `CreateTimestamped` used in the Harp package. Core proxy types have been leveraged to allow for automatic conversion of old workflows and the original type has been marked with the `[Obsolete]` attribute.
Fixes #1518
=> Rename CombineTimestamp to CreateTimestamped

Bonsai.Core.Tests/ExpressionBuilderGraphTests.cs, Bonsai.Core.Tests/TestWorkflow.cs, Bonsai.Core/Expressions/ExpressionBuilder.cs, Bonsai.Core/Expressions/ExpressionBuilderGraphExtensions.cs, Bonsai.Core/Expressions/ExternalizedDateTimeOffset.cs, Bonsai.Core/Expressions/ExternalizedProperty.cs, Bonsai.Core/Expressions/ExternalizedTimeSpan.cs
To support more flexible programmatic manipulation of expression builder workflows, this PR introduces a new overload to compile an expression builder graph into an observable sequence where the type of the elements in the sequence is known.
This makes it possible to load a workflow and perform a type-safe subscription to access the results of the compiled observable sequence, as shown in the example below:
```c#
using var reader = XmlReader.Create(path);
var workflowBuilder = (WorkflowBuilder)WorkflowBuilder.Serializer.Deserialize(reader);
var observable = workflowBuilder.Workflow.BuildObservable<object>();
```
Both covariance and explicit type conversions are allowed in case of type mismatch between the type of the compiled expression and the expected result type.
Fixes #1915
=> Allow building workflows as typed sequences

Bonsai.Core/Reactive/Timer.cs, Bonsai.Shaders/Timer.cs
Ignoring the value of `TimeSpan.Zero` for the `Period` property is an unfortunate historical legacy. The property should really expose a nullable type when deciding between which `Observable.Timer` overload to call.
This PR changes the type signature of `Period` to be a nullable timespan, but retains the same behavior by requiring `Period` to be larger than zero for periodic timers. We also introduce a slight modification to its serialization behavior to ensure that a value of zero is always serialized as `null`.
This will start the migration away from using `TimeSpan.Zero` as a valid value, and might give us some room to consider reinstating the zero period as a high frequency periodic timer for 3.0.
We could also introduce an automatic conversion at the level of the editor, but this …
=> Make period a nullable property of reactive timer and clarify documentation

.github/workflows/Bonsai.yml, Bonsai.Core.Tests/Bonsai.Core.Tests.csproj, Bonsai.Editor.Tests/Bonsai.Editor.Tests.csproj, Bonsai.System.Tests/Bonsai.System.Tests.csproj, tooling/Common.Tests.csproj.props, tooling/Common.csproj.props
This fixes a mistake made in https://github.com/bonsai-rx/bonsai/pull/1952
* `Bonsai.Editor.Tests` now targets `net8.0-windows` as appropriate
* Made the relevant NuGet warning into an error to avoid this mistake in the future
* Disabled running `net8.0-windows` tests on Linux
The last one was somewhat annoying as `dotnet test` doesn't have a great way to just run tests for all target frameworks except one or something similar. In the end I opted to run `net472`, `net8.0`, and `net8.0-windows` all as discrete steps (which will actually be kinda nice anyway.)
As a result, test projects are only allowed to target one of those three target frameworks. This is enforced by the build system in order to avoid the easy mistake of having an entire test suite skipped without knowing.
------------- …
=> Fix test target framework issues

Bonsai.Core.Tests/TestWorkflow.cs, Bonsai.Editor.Tests/Bonsai.Editor.Tests.csproj, Bonsai.Editor.Tests/WorkflowEditorTests.cs, Bonsai.Editor/GraphModel/WorkflowEditor.cs
Since build dependencies always affect their target node and are not considered proper inputs to operators, they should be excluded when estimating number of inputs to a newly created nested node.
Fixes #1792
=> Exclude build dependencies when counting inputs to new nested node

.github/workflows/Bonsai.yml
This allows CI to bypass the pull request requirement for pushing to `main`
This PR requires some manual repository configuration before merging.
=> Use deployment key in CI for manipulating Git repository

Bonsai.Core.Tests/TestWorkflow.cs, Bonsai.Editor.Tests/WorkflowEditorTests.cs
The workflow editor API requires the initial state to have all nodes topologically sorted to ensure reversibility of operations.
Here we move the sorting operation to the test infrastructure to facilitate reuse and avoid enforcing the sort in `MockGraphView` specifically to allow regression testing cases where the initial state may or may not be sorted (this is a limitation of the algorithm which we may want to remove in the future).
We also assert a missing invariant in a previous test.
=> Add support for sorting test workflows

Bonsai/App.manifest
Ever since [Windows 10 version 1607](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later) it has been possible to extend the maximum file path by setting the following registry value:
```reg
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem]
"LongPathsEnabled"=dword:00000001
```
However, applications also need to explicitly opt-in to long path support, which for .NET Framework is done via the `App.manifest` file. This PR explicitly adds the required `longPathAware` element to enable this support.
=> Add support for long paths on Windows

.github/workflows/create-build-matrix.py
GitHub [has resumed](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/) the rollout of bringing `ubuntu-latest` up to Ubuntu 24.04.
This breaks our unit tests on Linux due to Mono being dropped from the runner image due to [somewhat unfortunate reasons](https://www.github.com/actions/runner-images/issues/10636#issuecomment-2375010324).
The easiest solution for now is to just stick to Ubuntu 22.04, which still includes Mono. We can expect 22.04 to be supported by GitHub until October 2026 at the very least, most likely until April 2027. By then we will either hopefully A) not care about Mono anymore or B) the [recent migration of Mono to Wine](https://www.github.com/mono/mono/issues/21796) will mean more modern ways of acquiring …
=> Keep Linux builds on Ubuntu 22.04 for now

Bonsai.Dsp/MatrixWriter.cs
This PR expands the compatibility of `MatrixWriter` to any arbitrary sequence of [unmanaged types](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/unmanaged-types) by taking advantage of [`Buffer.MemoryCopy`](https://learn.microsoft.com/en-us/dotnet/api/system.buffer.memorycopy?view=net-9.0) to directly marshal the value type into a binary stream.
The new overload signature is:
```c#
public IObservable<TElement> Process<TElement>(IObservable<TElement> source) where TElement : unmanaged
```
`Buffer.MemoryCopy` is compatible across both .NET Framework and .NET 5+ but we might consider later improving the implementation for .NET 5+ by taking advantage of new memory copy performance primitives.
Fixes #1578
=> Add MatrixWriter overload for sequences of unmanaged types

Bonsai/Program.cs
When the `--export-image` flag was introduced we failed to ensure the editor is not launched during package restore. This PR fixes it by validating the launch editor flag against the state of the export image flag.
Fixes #2096
=> Avoid launching editor during image export

Bonsai.Core/Expressions/ExpressionBuilderGraphExtensions.cs, Bonsai.Editor/GraphView/WorkflowGraphView.cs, Bonsai.Editor/Layout/LayoutHelper.cs, Bonsai.Editor/Layout/VisualizerDialogLauncher.cs
A few visualizer assignment behaviors were broken by the changes in #1870. Specifically the way the active visualizer is obtained at runtime is no longer valid and needs to change to use the visualizer dialog map.
We also took this opportunity to correct the startup behavior of visualizer layouts described in #2071 and also the behavior of the show visualizer context menu, to ensure that if the selected visualizer is not visible but the drop down menu item is clicked, the dialog is shown or activated.
Fixes #2071 
Fixes #1841
=> Improve consistency of visualizer context menu

Bonsai.Editor/GraphModel/WorkflowEditor.cs
Added filters on ungroup, enable and disable operations so that only eligible nodes in a multi-selection will be included in the command. If no nodes are eligible the command will not execute and the command history will remain unchanged.
This has a secondary benefit that when calling undo on the operation, only affected nodes will be highlighted.
Fixes #2150
=> Remove idempotent operations from the undo history

Bonsai.Editor/EditorForm.cs
Similar to other IDE software, we should preserve the current editing environment even if no changes have been made to the underlying workflow. To do this we factor out the workflow settings serialization logic and run it on a clean editor shutdown, similar to persistence of global editor settings.
Fixes #2153
=> Save workflow settings when closing the editor

Bonsai.Editor.Tests/WorkflowEditorTests.cs, Bonsai.Editor/GraphModel/WorkflowEditor.cs
When ungrouping a graph node, nested nodes are first inserted in bulk onto the outer workflow, then connected to external edges. These extra connections may change the ordering of these ungrouped nodes in unpredictable ways. To ensure bulk removal is successful we need to restore the original order.
Fixes #2151
=> Ensure ordering before removing ungrouped nodes

Bonsai.Editor/Docking/WorkflowDockContent.cs, Bonsai.Editor/EditorForm.cs, Bonsai.Editor/GraphModel/WorkflowEditorPath.cs, Bonsai.Editor/GraphView/WorkflowEditorControl.cs, Bonsai.Editor/GraphView/WorkflowSelectionModel.cs
Closing all tabs would leave the selected view as a disposed control. These changes allow the selected view to be fully optional:
- safeguards are added where necessary, e.g. by using the null-coalescing operator
- default navigation behavior will create a tab when none is available
- fixed a number of outstanding issues with the Find command left from the editor refactoring
- fixed an outstanding issue where newly created tabs would not correctly highlight existing errors
- fixed an outstanding issue with saving workflow settings where the wrong path would be used when changing working directory
Where possible, reasonable default behavior was implemented to avoid propagation of null-handling concerns. For example, asking for the `ExpressionBuilderGraph` service will typically return the …
=> Improve navigation behavior when no tabs are open

Bonsai.Core.Tests/TestWorkflow.cs, Bonsai.Editor.Tests/EditorHelper.cs, Bonsai.Editor.Tests/WorkflowEditorTests.cs, Bonsai.Editor/GraphModel/WorkflowEditor.cs
The semantics of the node deletion action allow preserving connected paths whenever possible. Still, when a node receives multiple input arguments, it becomes ambiguous to decide which path should be continued.
However, this problem becomes again decidable if we also delete all the multiple input arguments in the same operation. To leverage this, we need to ensure the set of deleted nodes is topologically sorted, such that we delete all upstream nodes before downstream merge nodes.
Fixes #1523
=> Ensure topological sort before deletion

Bonsai.Editor/GraphView/WorkflowGraphView.cs
The default `ToolStripMenuItem` class uses the `Return` key to navigate to the next drop down level if nested drop down items are specified. Since this navigation can also be done via the arrow keys, we override the behavior of the `Return` key to always click the item, which is consistent with what happens when pressing the `Return` key and no drop down items are specified.
Fixes #1967
=> Allow selecting output menu items using keyboard

Bonsai.Core/Expressions/Properties/StringProperty.cs
Here we add a new `Value` property to the `StringProperty` class, and attach an `EditorAttribute` to the property declaration for the purposes of allowing editing of multi-line strings.
Fixes #2190
=> Add multiline string editor for string properties

Bonsai.Osc/Message.cs
To prevent issues with serializing data messages depending on the OS and machine culture, here we force the use of `string.Format` with invariant culture settings for all message contents.
Fixes #2184
=> Ensure OSC message format is culture invariant

Bonsai.Editor/DocumentationHelper.cs
When searching for operator documentation, the editor starts from the project URL specified in the operator package and the UID of the operator fully qualified type. For successful resolution to work, the project URL must currently host a `xrefmap.yml` file containing the specified UID inside.
For various reasons this ends up being impractical behavior for many projects. To begin with, it assumes all projects must be documented using [docfx](https://dotnet.github.io/docfx/), and that all projects went to the trouble of defining a complete reference documentation.
Instead, it is very often the case that documentation has still not been finalized for a project, and the project URL may simply be pointing to a version control repository, or that the developers of a package simply wish to …
=> Fallback to base url when no docs are found

Bonsai.Core.Tests/ExpressionBuilderGraphTests.cs, Bonsai.Core.Tests/TestWorkflow.cs, Bonsai.Core/Expressions/ExpressionBuilderGraphExtensions.cs
To avoid complicated edge cases with disabled branch logic we introduce new semantics where all fully disabled branches are removed from the build sequence.
A fully disabled branch is defined as any path ending in a disabled terminal node (i.e. a node with no outgoing edges) where all branches leaving from the path are also themselves fully disabled.
Fixes #2007
=> Prune all fully disabled branches during build

Bonsai.Editor/EditorForm.cs, Bonsai.Editor/GraphView/WorkflowEditorControl.cs, Bonsai.Editor/GraphView/WorkflowGraphView.cs
The contents of the annotation panel should be cleared if they relate to the specific workflow which has been cleared by the new action. If contents relate to browsing documentation pages, we leave them, as in this case no explicit link exists between the contents of the browser and the workflow.
Fixes #2067
=> Clear annotation panel on new workflow creation

Bonsai.Core.Tests/ExpressionBuilderGraphTests.cs, Bonsai.Core.Tests/ExpressionHelperTests.cs, Bonsai.Core.Tests/TestTypes.cs, Bonsai.Core/ExpressionHelper.cs, Bonsai.Core/Expressions/BinaryOperatorBuilder.cs, Bonsai.Core/Expressions/ExpressionBuilder.cs, Bonsai.Core/Expressions/GetValueOrDefaultBuilder.cs, Bonsai.Core/Expressions/HasFlagBuilder.cs, Bonsai.Core/Expressions/IndexBuilder.cs, Bonsai.Core/Expressions/WorkflowPropertyDescriptor.cs, Bonsai.Design.Visualizers/GraphHelper.cs
By default, the named overload to the [`Expression.Property`](https://learn.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression.property?view=net-9.0#system-linq-expressions-expression-property(system-linq-expressions-expression-system-string)) and [`Expression.PropertyOrField`](https://learn.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression.propertyorfield?view=net-9.0) methods may throw an exception when accessing a property or field that hides an inherited member with the same name, due to the default rules used by the underlying [`System.Type.GetProperty`](https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-type-getproperty) method where an `AmbiguousMatchException` is thrown.
Here we rewrite several uses of these named …
=> Ensure property mapping and member selector operators prefer derived properties

Bonsai.Editor/EditorForm.cs
Changes to the editor navigation model introduced in #1870 created a regression where initializing the editor layout will check for pending exceptions to highlight. If a previous workflow had been left with errors this would cause an unhandled exception since the old nodes are no longer present following successful opening of a new file.
Here we ensure workflow errors are cleared as soon as the workflow builder is set to the newly open file.
Fixes #2202
=> Ensure any workflow errors are cleared on open

Bonsai.Editor/EditorForm.cs
To make it easier to generate documentation images from existing workflow files, here we set the default export image name to match the workflow filename. If no file has been saved yet, the dialog will retain its current behavior of leaving the filename empty.
Fixes #1536
=> Use workflow filename as default export image name

Bonsai.Editor/GraphModel/ElementHelper.cs
Deprecated operators are hidden from the toolbox, but remain visible in workflows containing them.
While clearly distinguished by a visual hash, here we include any deprecation message embedded in the type metadata onto the operator description displayed by the property grid when the operator is selected.
This allows more information to be conveyed on how to deal with the obsolete operator going forward.
Fixes #2207
=> Add obsolete message to operator descriptions

Bonsai.Editor/EditorForm.cs, Bonsai.Editor/WorkflowDisposable.cs
Here we improve the consistency of the workflow shutdown sequence. Following a call to `StartWorkflow`, all errors are routed via the created observable sequence, whether they are errors thrown by the workflow build process itself or by any operator following successful subscription.
When any errors are raised, or when successfully completing the sequence, the editor running state must be cleared. Previously we tried distinguishing between different error exit paths, but this proved problematic since complex edge cases could cause multiple error handlers to be called simultaneously.
Here we aim to have a common final path to shutdown by tracking a single shared variable which is disposed when exiting the workflow sequence via any of the exceptional or successful termination routes.
Fixes …
=> Avoid multiple shutdown paths out of StartWorkflow

Bonsai.Editor/EditorForm.cs
Opening a new workflow requires clearing a number of validation stages following the initial load from file. Failing any of these stages requires aborting the load and reverting back to the current workflow. Here we store the candidate in a separate local until the entire validation and workflow preparation is complete.
Fixes #2230
=> Ensure editor workflow is not set until validation

Bonsai.Editor/EditorForm.cs, Bonsai.Editor/GraphModel/GraphNode.cs, Bonsai.Editor/Layout/VisualizerLayoutMap.cs
The workaround in ce64bc9a35558e294a25f8cde7edb31d24196aec for avoiding stack overflow when loading self-referential workflows was insufficient, as it preemptively returned `false` while failing to prepare the workflow and editor state adequately.
Here we replace this approach with a single validation of the workflow, while fixing issues with self-reference by avoiding indirect loading of cyclic workflows. The following issues were resolved:
- Workflows which fail to build are not shown in the editor due to early exit (692794fe4783bc77053ba7756adbb9ea9d1a8156)
- Layout fails to serialize in self-referential workflows due to null workflow references (f5cfd9c9623c87fb283a09d1023f3ce094f7a779)
- Self-referential include chains allow manual navigation in the editor …
=> Avoid corrupting editor state when loading workflow with circular includes

Bonsai.Editor/GraphView/WorkflowGraphView.cs
Disabled nodes should be treated akin to commented out code. Context menu actions and other editor actions other than branching should be disallowed to prevent accidental creation of confusing workflows.
Fixes #2238
=> Disable confusing editor actions on disabled nodes

Bonsai.Editor/EditorForm.cs, Bonsai.Editor/IWorkflowEditorService.cs
Here we refactor the initialization of toolbox and visualizer modules as an async task and integrate it into the process of opening a workflow. This is to ensure all visualizer types are loaded before validating the layout assignments.
To do this we refactored several asynchronous initialization and monitoring tasks which previously were implemented as observable sequences. A shared cancellation token tied to form closing is introduced as a way to cancel all tasks on exit. 
Because continuations should automatically capture the form dispatcher there is no need for explicit locking.
Fixes #2229
=> Await initialization before loading layout

Bonsai.Design/ObjectTextVisualizer.cs
Setting a minimum size can cause layout problems when composing multiple visualizers in containers.
Fixes #2252
=> Avoid setting minimum size on text visualizer

Bonsai.Editor/EditorForm.cs, Bonsai.Editor/GraphView/WorkflowEditorControl.cs
This ensures that all include workflows have been expanded in case any editor dock panel is targeting their contents.
Fixes #2254
=> Initialize editor layout after workflow validation

Bonsai.Core/Expressions/ExpressionBuilderGraphExtensions.cs, Bonsai.Core/Expressions/ISupportPropertyAssignment.cs, Bonsai.Core/Expressions/IncludeWorkflowBuilder.cs, Bonsai.Core/Expressions/TypeMapping.cs, Bonsai.Core/Expressions/VisualizerMappingBuilder.cs, Bonsai.Core/Expressions/VisualizerMappingExpressionBuilder.cs, Bonsai.Core/Expressions/WorkflowExpressionBuilder.cs, Bonsai.Core/Properties/AssemblyInfo.cs, Bonsai.Core/Properties/Resources.Designer.cs, Bonsai.Core/Properties/Resources.resx, Bonsai.Design/Properties/AssemblyInfo.cs, Bonsai.Design/VisualizerWindow.cs, Bonsai.Editor/GraphView/WorkflowGraphView.Designer.cs, Bonsai.Editor/GraphView/WorkflowGraphView.cs, Bonsai.Editor/Layout/DialogLauncher.cs, Bonsai.Editor/Layout/VisualizerDialogSettings.cs, Bonsai.Editor/Layout/VisualizerLayoutMap.cs
This operator allows declaring which specific visualizer windows should be launched on workflow start, and makes it possible to have frontend applications launch correctly even in the absence of a visualizer layout file.
The new `VisualizerWindow` operator does not allow changing the visualizer type at runtime, but it is possible to relaunch the window from the context menu in case it is closed.
Note that while basic window settings may be cached in the local layout file, runtime visualizer settings are not currently saved for explicitly launched visualizers. If required, such logic should be embedded in the frontend UI itself.
`VisualizerWindow` properties which are explicitly set will always overrule the cache.
Fixes #2137
=> Add new VisualizerWindow operator

Bonsai.Shaders/ITextureArray.cs, Bonsai.Shaders/TextureArray.cs, Bonsai.Shaders/TextureSequence.cs
As discussed in #1968 and #1999, there is often a need to explicitly access the array of textures stored in a texture sequence for custom purposes. Here we provide a new interface `ITextureArray` matching the already public class `TextureArray` and also provide an adapter to this interface via the `TextureSequence` class.
This allows downcasting from a texture sequence into `ITextureArray` for the purposes of accessing the internal texture handles:
```c#
if (window.ResourceManager.Load<Texture>(name) is ITextureArray array)
{
for (int i = 0; i < array.Length; i++)
GL.BindTexture(TextureTarget, array[i]);
}
```
Fixes #1968
=> Expose texture array interface on texture sequence

Bonsai.Configuration.Tests/AssemblyInfo.cs, Bonsai.Configuration.Tests/Bonsai.Configuration.Tests.csproj, Bonsai.Configuration.Tests/ScriptExtensionsProjectMetadataTests.cs, Bonsai.Configuration.Tests/ScriptExtensionsTests.cs, Bonsai.Configuration.Tests/TestHelpers.cs, Bonsai.Configuration/ScriptExtensions.cs, Bonsai.Configuration/ScriptExtensionsProjectMetadata.cs, Bonsai.Editor/Properties/AssemblyInfo.cs, Bonsai.sln, tooling/Common.csproj.props, tooling/Common.csproj.targets
Was initially focused on https://github.com/bonsai-rx/bonsai/issues/2055, which was caused by an oversight done when refactoring the several redundant XML parsing entrypoints during https://github.com/bonsai-rx/bonsai/pull/1753 (Prior to the refactor, all of them stripped whitespace *except* for the one that loaded the project for adding package references. That exception was lost in the refactor.)
While I was at it I wrote a suite of unit tests related to the handling of `Extensions.csproj` and fixed some other issues I found along the way.
* Fix whitespace being stripped during automatic updates
* Fix fresh `Extensions.csproj` always being written with CRLF newlines
* Fix `ScriptExtensionsProjectMetadata` not actually being immutable as intended
* Fix adding redundant `ItemGroup` when …
=> Fix various issues with `Extensions.csproj` handling and add unit testing for it

Bonsai.Core/Expressions/ExpressionBuilder.cs, Bonsai.Core/Expressions/ExpressionBuilderGraphExtensions.cs, Bonsai.Editor/Layout/LayoutHelper.cs, Bonsai.Vision.Design/BinaryRegionExtremesVisualizer.cs, Bonsai.Vision.Design/CircleVisualizer.cs, Bonsai.Vision.Design/LineSegmentVisualizer.cs, Bonsai.Vision.Design/VisualizerHelper.cs
Specific visualizers may require accessing inputs from the predecessor node, which are found from a search through the workflow in which the visualizer is embedded. However, if the visualizer is being propagated upwards through nested scopes or mapped into other containers, this association between the visualizer source and its predecessor can be lost.
This fix uses `ITypeVisualizerContext` to identify the correct source of visualizer data, and then relies on visualizer and visualizer mapping propagation semantics to guide a recursive search for the correct predecessor and ensure the association is preserved.
Fixes #2251
=> Ensure visualizer predecessor search can extend to nested scopes

Bonsai.Core/Expressions/BinaryOperatorBuilder.cs, Bonsai.Core/Expressions/OperandCombinatorExpressionBuilder.cs, Bonsai.Core/Reactive/Append.cs, Bonsai.Core/Reactive/Prepend.cs
There are many cases in which empty sequences may cause undesired behavior due to downstream operator constraints enforcing a minimum of one value for successful processing (e.g. see #1617). Similarly, it can also be useful to enforce that a sequence always ends with a specific value, no matter when it terminates.
For both of these cases the `Prepend` and `Append` operators can be very convenient. Although equivalent behavior may be obtained using `Concat` and similar observable combinators, the convenience of `Prepend` and `Append` lays in the fact that the desired value can be specified inline with the sequence itself, without requiring merging of external sequences.
The current limitation is that any such appended or prepended values must be XML serializable as they will be stored …
=> Add support for Prepend and Append operators

Bonsai.Editor/GraphModel/GraphNode.cs
Extracting the argument range of an editor graph node suffered a regression in #2235 due to a logical error specifying operator precedence.
Fixes #2283
=> Ensure node argument range indicator is displayed

Bonsai.Core.Tests/OverloadedCombinatorBuilderTests.cs, Bonsai.Core/Expressions/CombinatorBuilder.cs, Bonsai.Core/Expressions/ExpressionBuilder.cs
Handling method overload resolution with variable length parameters was relying on specific edge cases. This PR attempts to resolve this by correctly checking for `params` expansion during overload resolution phase, and improving the way the lower bound for the combinator argument range is computed by taking into account whether a method with a single `params` contains unassigned generic parameters.
Specifically this allows defining operators with a single non-generic overload with `params`, e.g.:
```c#
public IObservable<int> Process(params IObservable<int>[] sources)
```
Unit tests were added which may help to guide discovery and resolution of future edge cases related to methods with hybrid variable length generic overloads.
Fixes #2280
=> Account for variable length parameters correctly

Bonsai.NuGet.Design/PackageViewController.cs
Tree view selection changes can transiently report a null selected node. The conditions causing this on refresh can be difficult to determine, but in general we want to account for this possibility and treat it identical to a null package and hide the details.
Fixes #2288
=> Add missing null guard in SelectPackageDetails

.gitattributes
By default GitHub collapses designer files in PRs because they're "generated". IMO they don't really count as generated though, and having them collapse makes it easy to overlook changes to the UI.
I finally got annoyed enough to actually read [the documentation](https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github) (or maybe they recently added the link to collapsed files) and it turns out you can disable the functionality, which this PR does.
If you're not sure what I'm talking about, compare the changes on these two PRs:
* [Before](https://github.com/NgrDavid/bonsai/pull/2/files)
* [After](https://github.com/NgrDavid/bonsai/pull/3/files)
We might also consider just disabling the automatic generated file detection …
=> Avoid collapsing WinForms designer files in the PR review UI

Bonsai.NuGet.Design/GalleryDialog.cs, Bonsai.NuGet.Design/PackageManagerDialog.cs
Hiding the parent window when launching a modal dialog is a confusing design given that it is both unexpected, and creates a series of annoying side-effects such as hiding the taskbar for the application.
Here we revert the dialog to standard modal behavior.
Fixes #2296
=> Make package source configuration dialog a true modal window

Bonsai.Dsp/MatrixReader.cs
Buffer length is calculated in samples per channel so we need to divide by channel count to correctly get the number of samples in the whole file.
Fixes #2300
=> Allow multi-channel data when reading whole files using MatrixReader

Bonsai.Configuration.Tests/Bonsai.Configuration.Tests.csproj, Bonsai.Core.Tests/Bonsai.Core.Tests.csproj, Bonsai.Editor.Tests/Bonsai.Editor.Tests.csproj, Bonsai.Editor/Bonsai.Editor.csproj, Bonsai.Editor/Properties/Resources.Designer.cs, Bonsai.NuGet/Bonsai.NuGet.csproj, Bonsai.System.Tests/Bonsai.System.Tests.csproj, Bonsai.Vision/LoadExtrinsics.cs, Bonsai.Vision/LoadIntrinsics.cs, Bonsai.Vision/SaveExtrinsics.cs, Bonsai.Vision/SaveIntrinsics.cs, Bonsai/Bonsai.csproj, Bonsai32/Bonsai32.csproj
Here we perform maintenance upstream dependency updates. A few packages were left behind either because of known issues, e.g. WebView2 (https://github.com/MicrosoftEdge/WebView2Feedback/issues/4924), or to avoid moving into .NET 9 runtime packages.
Upgrading YamlDotNet also motivated fixing file name editor extension strings in a few places.
=> Update upstream dependencies

Bonsai.Audio/README.md, Bonsai.Core/README.md, Bonsai.Design.Visualizers/README.md, Bonsai.Design/README.md, Bonsai.Dsp.Design/README.md, Bonsai.Dsp/README.md, Bonsai.Editor/README.md, Bonsai.Osc/README.md, Bonsai.Player/README.md, Bonsai.Scripting.Expressions.Design/README.md, Bonsai.Scripting.Expressions/README.md, Bonsai.Shaders.Design/README.md, Bonsai.Shaders.Rendering/README.md, Bonsai.Shaders/README.md, Bonsai.StarterPack/README.md, Bonsai.System.Design/README.md, Bonsai.System/README.md, Bonsai.Templates/README.md, Bonsai.Vision.Design/README.md, Bonsai.Vision/README.md, Bonsai.Windows.Input/README.md, Bonsai/README.md
As a compound adjective it should be hyphenated, but not when used as a compound noun in a sentence.
=> Update spelling of open source to match convention

Bonsai.Shaders/WarpPerspective.cs, Bonsai.Vision/CropPolygon.cs, Bonsai.Vision/Drawing/CropCanvas.cs, Bonsai.Vision/GoodFeaturesToTrack.cs
Wherever reasonable we want to add default properties to make it easier to launch visual editors from the workflow itself.
=> Add missing editor default properties

Bonsai.Editor/EditorForm.Designer.cs, Bonsai.Editor/EditorForm.cs, Bonsai.Editor/GraphView/WorkflowGraphView.Designer.cs, Bonsai.Editor/GraphView/WorkflowGraphView.cs
To avoid ambiguity with the meaning of **Save As Workflow** we rename the title of the menu item to **Save As Extension**.
Fixes #2356
=> Rename save workflow extension menu item

Bonsai.Editor/EditorForm.Designer.cs
Still has the old keyboard shortcut rather than the new one.
=> Fix tooltip for `New` workflow button on toolbar
